### ISSUE TITLE
As an operator, I want an app to test logging during the v13 upgrade.

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-deploy-cf#490]
In order to quantify log duplication and potential log loss during the cf-deployment v13 upgrade(https://github.com/cloud-gov/cg-deploy-cf/issues/487), I want a simple app that logs regularly. 

## Acceptance Criteria

- [x] App should emit 2 log messages per second
- [x] Log messages should have unique, sequential ids to aid in identifying duplicates or loss in logging systems
- [x] Log messages should include the id of the cell the app instances are running on. This should be fetched once on startup by curling the CF api.

--- 

## Security considerations

None

**Comment by bengerman13** [comment]
fixed in cloud-gov/log-spammer#1
