### ISSUE TITLE
As an operator, I want an app that serves as a syslog endpoint

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-deploy-cf#491]
In order to test log duplication and loss via log-drains during the v13 cf-deployment upgrade, we need an app to serve as syslog drain endpoint to capture log messages

## Acceptance Criteria

* Logs should be persistent (a db is fine) so that we can execute queries to identify loss or duplication.

--- 

## Security considerations

This endpoint should only be used with the log generator app: https://github.com/cloud-gov/cg-deploy-cf/issues/490.  Therefore the data will not be sensitive.

**Comment by bengerman13** [comment]
Since we don't allow TCP routes, this will need to be either not in CF, or an HTTPS drain. I don't yet understand how HTTPS drains work, so I'll need to do more digging there

**Comment by spgreenberg** [comment]
HTTPS is just the protocol of the drain. It is transparent to the user and the apps. If you create the drain with `cf cups -l https://` cf will make HTTP calls to post log messages to the endpoint.

If we want to test syslog, my assumption would be that we bosh deploy or simply manually deploy the drain on EC2.

**Comment by bengerman13** [comment]
I *think* the thing to do to get this done fastest and with most reusability is to use a CF app and use an https drain

**Comment by pburkholder** [comment]
If it makes anything easier, it is OK by my to ship dummy logs to a commercial log service.

**Comment by spgreenberg** [comment]
https://github.com/cloud-gov/log-drain-endpoint
