### ISSUE TITLE
Increase platform's app disk capacity

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/cg-deploy-cf#492]
In order to increase the platform's app ephemeral disk capacity to support Federalist customers, we want increase the max app disk space and add additional ephemeral disk space to the diego cells to support the increase in app disk space.

## Acceptance Criteria
* [x] Given this impacts the entire platform, we want consensus from the operators on the appropriate increases.
* [x] Given the current `maximum_app_disk_in_mb`, we want to increase form 4096MB to 6144MB(proposed)
* [x] Given the current `diego cell disk`, we want to increase from 200GB to 250GB(proposed 25% increase)

--- 

## Security considerations
none

### Background
- [Estimates](https://docs.google.com/document/d/1CR4nnf825cxCkOCVByF0F8cGn0A-NibmisZwfKfT1Bc/edit)
- [Previous issue](https://github.com/cloud-gov/product/issues/1374)

### Config updates
* [ ] Update `maximum_app_disk_in_mb` in [opsfile](https://github.com/cloud-gov/cg-deploy-cf/blob/14d03acd7bd9887632023f41e59db769475c1a6a/bosh/opsfiles/api-defaults.yml#L9-L11) from  4096MB to 6144MB
* [ ] Update `diego cell ephemeral disk` in [opsfile](https://github.com/cloud-gov/cg-deploy-cf/blob/14d03acd7bd9887632023f41e59db769475c1a6a/bosh/opsfiles/diego-cell-disk.yml) from  200GB to 250GB

**Comment by karareinsel** [comment]
Work on this will resume on 8/11.

**Comment by ChrisMcGowan** [comment]
Changes to deployment repo: https://github.com/cloud-gov/cg-deploy-cf/pull/497
Deployed itself in prod: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cf/jobs/deploy-cf-production/builds/221
