### ISSUE TITLE
Issue with trusted CA certs not being replaced

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/cg-deploy-cf#494]
While attempting to renew a certificate in the dev environment that was expiring, we realized that it isn't needed at all.  We were able to delete the cert, but it's configuration in Credhub is still in place for some reason.

It appears that [lines 34 - 38 in this ops file](https://github.com/cloud-gov/cg-deploy-cf/blob/master/bosh/opsfiles/disable-secure-service-credentials.yml#L34-L38) are not performing the replacement they ought to be.  One possible cause is that the path changed in the parent config file that these replacement configurations overwrite.

@ChrisMcGowan or @soutenniza, do either of you have the link handy of that parent file in the Cloud Foundry repo?  I thought I copied it when we were resolving this but I don't appear to have it in my notes.  Also, if there's anything else I missed please feel free to add or correct.  Thanks!

## Security considerations
None:  This is an update to our open-source configuration so that the functionality works properly again.

## Implementation sketch
- [x] Update the `replace` configuration so that the cert doesn't get inserted back into Credhub

**Comment by soutenniza** [comment]
https://github.com/cloudfoundry/cf-deployment/blob/2ce048139541c3cafe47475f521111a9c131dacd/cf-deployment.yml#L1560

**Comment by spgreenberg** [comment]
@ccostino I think the ops file is working at least in the case of the `credhub_tls` cert. We had missed replacing one additional value.  You can see the fix here: https://github.com/cloud-gov/cg-deploy-cf/pull/495. This has been tested in dev so far w/ the value removed from credhub.

**Comment by ChrisMcGowan** [comment]
PR to fix last piece: https://github.com/cloud-gov/cg-deploy-cf/pull/502
