### ISSUE TITLE
Add Dockerhub Credentials to Concourse

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-deploy-cf#513]
With the new Dockerhub account obtained, we need to distribute account credentials to any piece of our infrastructure that pulls images from Dockerhub so that rate limiting won't kick in. (Work originally outlined in [this issue](https://github.com/cloud-gov/product/issues/1476)).

**Comment by bengerman13** [comment]
This is no longer needed, since we're pulling images through our caching proxy
