### ISSUE TITLE
Investigate IDP unavailability crashing UAA

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-deploy-cf#522]
See issue: https://github.com/cloudfoundry/uaa/issues/1531 and https://www.pivotaltracker.com/n/projects/997278/stories/177224767

Goal: Are we able to provide a PR to fix this?

## Security considerations

We are concerned that this may not be patched quickly. It leaves UAA vulnerable to issues that could cause platform users and operators to not be able to log in.

**Comment by spgreenberg** [comment]
Running list of notes:

- The exception is being caught, logged and thrown. I am not sure why this would cause a restart as this is a normal java flow. catch block: https://github.com/cloudfoundry/uaa/blob/716b5948a6ae3b1beccd8af2906b09fbb29f8213/server/src/main/java/org/cloudfoundry/identity/uaa/cache/ExpiringUrlCache.java#L79. 
- This exception extends from RestClientException so the above block does catch it: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/ResourceAccessException.html

**Comment by spgreenberg** [comment]
From: https://docs.cloudfoundry.org/uaa/identity-providers.html 

- If the IDP is configured using a URL, UAA refreshes the metadata content from that URL every 10 minutes. This is useful for providers that rotate their keys frequently.

- [ ] Can we therefore extend the TTL on a cache record if an update fetch fails?

**Comment by spgreenberg** [comment]
We could likely implement this interface: https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/cache/UrlContentCache.java

To allow the old cache record to be marked stale but still be valid.

**Comment by spgreenberg** [comment]
Plan: Implement the above interface with the following cache properties:

- If a metadata update fails, mark the cache record as stale but return the existing information. This should break the current infinite loop of retrying.
- Update the TTL on the cache record to some future date when it will be tried again.
- Update a count on the number of metadata update retries.
- Expose metrics on failed IDP refreshes that could be alerted on in Prometheus

If a configurable threshold of retry attempts occurs, remove the IDP. 

- We need to figure out where this would be as it should not be in the UrlContentCache implementation
- We realize a deployment will cause the IDP to be added back. However, this seems ok as the same back off process above would occur. 

If we don't remove the IDP and keep retrying, it is possible a nefarious actor could intercept the IDP and do bad things.

**Comment by spgreenberg** [comment]
https://github.com/cloudfoundry/uaa/pull/1563

**Comment by ccostino** [comment]
Looks like we received a review on this! https://github.com/cloudfoundry/uaa/pull/1563#pullrequestreview-680349719

**Comment by ChrisMcGowan** [comment]
Left an updated comment for the reviewer to hopefully get this approved/merged/closed.

**Comment by ChrisMcGowan** [comment]
Thanks @Dark-Knight-999 on the review - I let the maintainer know we where good with the change.

Moving this back to blocked until their merge the PR and a new UAA release is cut and deployed in our environment.

**Comment by ChrisMcGowan** [comment]
They merged the PR into develop branch.  Need to track main and when a release is cut now with the fix

**Comment by ccostino** [comment]
Awesome, thanks @ChrisMcGowan and @Dark-Knight-999!
