### ISSUE TITLE
(CG285-AU-5) Isolate UAA traffic from application load

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-deploy-cf#541]
In order to protect uaa from attacks on apps, we want requests for UAA to not go through the same gorouters as requests for apps.

This needs to be fleshed out a little more, and can't be picked up until cloud-gov/product#1426 is done

--- 

## Security considerations
This should improve our resilience against DoS-type attacks
To make sure we don't regress on HSTS, etc, we should probably add secureproxy to the UAA instance.

## Implementation sketch
We initially sketched this out as not having gorouters for uaa, which is certainly an option. We could also potentially have a separate gorouter group dedicated to uaa only, or to everything under fr.cloud.gov. 
The [isolation segment routing docs](https://docs.cloudfoundry.org/adminguide/routing-is.html#overview) will probably be helpful here

The upshot to keeping a set of gorouters is primarily that it's how CF is expected to run. The gorouters also provide us some of our controls about request timeouts and other limits, and are the best-formatted logs we get

**Comment by pburkholder** [comment]
Is this work we want to take on this month? It's related to CG285-AU-5 (and it's overdue...)

**Comment by pburkholder** [comment]
Do we still want to take on this work? 
> we want the UAA ALB to point directly at the UAA bosh VM, rather than going through the gorouters

**Comment by pburkholder** [comment]
This is sill an open POA&M, CG285-AU-5, it would be cool if we could close it (July?)

**Comment by pburkholder** [comment]
@mogul This is one of our very late POA&Ms and would be both an operational, security and compliance win to get addressed. Seems like the work involved is pretty modest. Can we put this on the path to completion?

**Comment by mogul** [comment]
I've added it to the cf-team board and pushed it near the top of the backlog.

**Comment by mogul** [comment]
@ChrisMcGowan can you take a look at this and give us an idea how much work it might be (and if it's white noise, just take care of it)?

**Comment by ChrisMcGowan** [comment]
So needed steps to complete this
-[ ] Create UAA ALB in all environments
-[ ] Create DNS entries for UAA & login in all environments
-[ ] Create target groups for new UAA ALBs 
-[ ] Update BOSH Cloud config to add vm extensions for new target groups 
-[ ] Create new gorouter pool via ops file
-[ ] Modify UAA route register to register its routes with new gorouter pool

**Comment by ChrisMcGowan** [comment]
@mogul @pburkholder 

Good news is the first three are already done and have been done expect it's target pool is just the existing gorouter pool. The alb also already has the basic waf core ruleset on it as well.
 
We'll need to modify the cloud-config to make a new VM extension and then modify cg-provision to change that output. It's there now but added to the main pool.

**Comment by mogul** [comment]
Per sync today there might still be another week or two of work needed for this. We are going to continue on with it.

**Comment by pburkholder** [comment]
@ChrisMcGowan Can you work on this in your next few weeks?

**Comment by pburkholder** [comment]
👋 ANy progress here? @jameshochadel  and @rcgottlieb should be included for visibility.

**Comment by pburkholder** [comment]
@ChrisMcGowan Can you weigh in on what should happen here while you're still around? Thanks

**Comment by ChrisMcGowan** [comment]
Working on this today but won't be able to execute it, hence the removal and move back to backlog.

**Comment by pburkholder** [comment]
@soutenniza @markdboyd @rbogle -- Is this UAA isolation work part of the DDOS work we have underway?

**Comment by markdboyd** [comment]
@pburkholder This work is part of the general [AWS Security Improvements](https://github.com/cloud-gov/product/issues/2272) epic and is slated for sprint 32.5

**Comment by pburkholder** [comment]
@ChrisMcGowan Is this in scope for this sprint or next?

**Comment by ChrisMcGowan** [comment]
@pburkholder it's going into the next sprint starting next week. 

The majority of the work is done already:

- [ ] Create and publish environment level ELBs via cg-provision
- [ ] Make DNS entries for `uaa.*` and `login.*` to point at correct ELBs via cg-provision
- [ ] Make environment specific target groups to use for each ELB vis cg-provision
- [ ] Modify and assign `vm_extension` for new ELBs in each environment via cg-provision and cg-deploy-bosh

This is current state.  For now the new `target groups` use the existing `gorouter` pools used by uaa, main, and apps ELBs.

To finish:

- [ ] Build new `cg-deploy-cf` task in each environment deploy to use `bosh int cf-deployment.yml --path /instance_groups/name=router` to pull out current state of the `router` job and create a new ops file.
- [ ] Make additional ops files to make a second gorouter instance group called `router_main` and then apply existing cg-deploy-cf ops files that effect router do this new job group
- [ ] Merge in this new `router_main` job into existing CF deployments - min # of VMs should be 2 but prod should probably be 4
- [ ] Update cg-provision to move `vm_extension` for BOSH cloud config to the new `router_main` group
- [ ] Deploy CF again while watching the target group to watch memebership change from old routers to new VMs for `router_main`
- [ ] Test login function - GSA SSO along with cloud.gov IDP to validate in logs that traffic now flows through dedicated UAA ELB and `router_main` instance group VMs
- [ ] Verify `router_main` syslog and AWSLogs show in logs-platform and in AWS CloudWatch as expected

Future work:

- [ ] Update cg-provision to move `api.*` DNS records over to this ELB so API/UAA traffic is isolated
- [ ] Create new AWS WAF Policy that's more unique and hardened then the main policy to better protect UAA/API endpoint vs customer apps

**Comment by cweibel** [comment]
Rolled out to prod with:

 - https://ci.fr.cloud.gov/teams/main/pipelines/terraform-provision/jobs/bootstrap-production/builds/349
 - https://ci.fr.cloud.gov/teams/main/pipelines/deploy-bosh/jobs/deploy-production-bosh/builds/1629
 - https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cf/jobs/deploy-cf-production/builds/405
 - https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cf/jobs/deploy-cf-production/builds/406
