### ISSUE TITLE
Test egress filter hypotheses

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-deploy-cf#565]
So we know if our egress filtering plan works, test out some of the theories.

## The plan, roughly:

- Global default egress policy allows no access (does this include the services network?)
- going forward, orgs get spaces with wide-open egress policy and without
- users in orgs can choose whether to put their apps in wide-open spaces, or in closed spaces, or both to create filtering proxies

To migrate, we think we want to add a new wide-open policy, map it to every existing org/space, and then change the global default

## what we need to test
- Does changing the global default change existing orgs/spaces?
- if so, when?
- does adding the wide-open policy ahead of time prevent this?

**Comment by bengerman13** [comment]
Note that this is only for runtime ASGs, not compile-time ASGs

**Comment by apburnes** [comment]
Initially tested the unbinding the assigned global ASG's to a space, the unbind action successfully completes, but the global ASG's persist. Since ASG's are only allow rules and updated ASG's do not take affect until app restart/restage, we may want to create a new, non-global ASG to allow all public traffic, apply it to every space, and then remove the global version of the allow all public traffic.

**Comment by bengerman13** [comment]
@apburnes that's what I was thinking. I have more details about how to cut over in the [ADR](https://github.com/cloud-gov/product/blob/egress-adr/adr/ADR-0001-egress-control.md?plain=true#L52-L56)

**Comment by apburnes** [comment]
#567 is creating duplicate ASG's of the public networks and dns. Working on a script to apply ASG's to all spaces.

**Comment by apburnes** [comment]
Testing works as expected when following the outlined [steps](https://github.com/cloud-gov/product/blob/egress-adr/adr/ADR-0001-egress-control.md?plain=true#L52-L56)

**Comment by apburnes** [comment]
Closing to work on transition steps in #568
