### ISSUE TITLE
Rotate AWS rds CA (Due May 2022)

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-deploy-cf#599]
The AWS RDS CA expires May 2022, so we need to update it when the new cert is available.
We should announce this in our news and on statuspage.

**Comment by ChrisMcGowan** [comment]
PR is in: https://github.com/cloud-gov/cg-deploy-cf/pull/623

**Comment by ChrisMcGowan** [comment]
Found a later ops file was over writing and removing RDS certs so 2nd PR to fix https://github.com/cloud-gov/cg-deploy-cf/pull/625
